"""
Numerical regression fixtures for the live Scapy extractor.

IMPORTANT:
These expected vectors are an independent oracle calculated from the published
CICFlowMeter V4 BasicFlow/FlowFeature semantics. They are NOT claimed to be
generated by executing the Java binary in this environment.

Once the actual CICFlowMeter Java tool is available, regenerate/replace the
expected vectors from its CSV output and keep these same deterministic packet
cases.
"""

import json
from pathlib import Path
import sys

import numpy as np
import pytest

try:
    from scapy.all import IP, TCP, Raw
except ImportError:
    pytest.skip("Scapy is required for live feature parity fixtures", allow_module_level=True)

# Adjust this when copying into backend/tests.
HERE = Path(__file__).resolve()
for candidate in (HERE.parent.parent, HERE.parent, Path("/mnt/data")):
    if (candidate / "src" / "ids_pipeline.py").exists() or (candidate / "ids_pipeline.py").exists():
        sys.path.insert(0, str(candidate))
        break

try:
    from src.ids_pipeline import RealTimeIDSPipeline
except ImportError:
    from ids_pipeline import RealTimeIDSPipeline

FIXTURE_PATH = Path("/mnt/data/cicflowmeter_reference_fixtures.json")
if not FIXTURE_PATH.exists():
    FIXTURE_PATH = HERE.parent / "cicflowmeter_reference_fixtures.json"

with FIXTURE_PATH.open(encoding="utf-8") as f:
    FIXTURES = json.load(f)


def _packet(spec):
    """Build a deterministic IPv4/TCP packet with a populated IP length."""
    p = IP(src="10.0.0.1", dst="10.0.0.2") / TCP(
        sport=12345,
        dport=80,
        flags=spec["flags"],
        window=spec["window"] if spec["window"] is not None else 0,
        dataofs=spec["tcp_header_len"] // 4,
    )
    payload_len = spec["payload_len"]
    if payload_len:
        p = p / Raw(b"X" * payload_len)

    # Force Scapy to calculate IP.len/dataofs before the live extractor sees it.
    p = IP(bytes(p))
    p.time = spec["time_s"]

    if spec["direction"] == "bwd":
        p[IP].src, p[IP].dst = p[IP].dst, p[IP].src
        p[TCP].sport, p[TCP].dport = p[TCP].dport, p[TCP].sport
        p = IP(bytes(p))
        p.time = spec["time_s"]

    return p


def _pipeline_with_flow(case):
    pipeline = object.__new__(RealTimeIDSPipeline)
    packets = []
    for spec in case["packets"]:
        packets.append((_packet(spec), spec["direction"] == "fwd"))

    # The extractor only needs the packet_list and initial destination port.
    flow_key = ("fixture", case["packets"][0]["time_s"])
    bwd_windows = [
        p["window"]
        for p in case["packets"]
        if p["direction"] == "bwd" and p["window"] is not None
    ]

    pipeline.flow_tracker = {
        flow_key: {
            "packet_list": packets,
            "init_dport": 80,
            "fwd_win": case["packets"][0]["window"],
            "bwd_win": bwd_windows[-1] if bwd_windows else None,
            }
        }
    return pipeline, flow_key


@pytest.mark.parametrize("case_name", sorted(FIXTURES["cases"]))
def test_scapy_matches_cicflowmeter_reference_fixture(case_name):
    case = FIXTURES["cases"][case_name]
    pipeline, flow_key = _pipeline_with_flow(case)

    actual = pipeline._extract_flow_features(flow_key)
    expected = np.asarray(case["expected"], dtype=float)
 
    assert actual.shape == (78,)
                
    np.testing.assert_allclose(
        actual,
        expected,
        rtol=1e-6,
        atol=1e-4,
        err_msg=f"CICFlowMeter reference mismatch in fixture {case_name}",
    )
